### ISSUE TITLE
Vault of the Incarnates

### ISSUE THREAD

**Issue by mario-64** [Ghezzo/BossesKilledLFR#2]
Bosses for Vault of the Incarnates aren't showing in the addon. LFR opened last week. No tabs are showing. Please update for Dragonflight. Thank you.

**Comment by CherylAoife** [comment]
Same for me.

**Comment by CherylAoife** [comment]
Added the following code to the raid_data.lua file starting at line 132:

-- Vault of the Incarnates
[2370] = { numEncounters = 3, startFrom =  1 }, -- The Primal Bulwark
[2371] = { numEncounters = 3, startFrom =  1 }, -- Caverns of Infusion
[2372] = { numEncounters = 2, startFrom =  1 }, -- Fury of the Storm

**Comment by mario-64** [comment]
I added these entries and still get no tabs for the new raids. Is there more which has to be added?

**Comment by CherylAoife** [comment]
Hmm. This is what lines 131 to 136 at the end of my file look like:

![image](https://user-images.githubusercontent.com/72202650/213281818-13a62b30-4e3f-47fa-87f8-2d4b31717ded.png)

And here's the result in-game:

![image](https://user-images.githubusercontent.com/72202650/213284551-a7178085-4a3f-4af1-9add-12dd12bf843b.png)

**Comment by mario-64** [comment]
Thanks! Got mine working. BTW, how'd you get the 2370, 2371 and 2372 values to use?

**Comment by CherylAoife** [comment]
I looked in another addon that I thought might use Raid IDs - and then compared the Shadowlands Raid IDs in this addon with the Shadowlands Raid IDs in the other addon to make sure they were the same. And then took the Dragonflight Raid IDs from the other addon and plugged them into the raid_data.lua file to see if they worked - and they did!

**Comment by mario-64** [comment]
Ok cool. I was just thinking ahead to when wing 4 and subsequent Dragonflight raids become available. We’ll have to do this again since it seems this add on has been abandoned.

**Comment by CherylAoife** [comment]
Actually, Ghezzo posted a reply on CurseForge that he will update today (19th Jan).
