### ISSUE TITLE
Raid tabs not grouped together

### ISSUE THREAD

**Issue by mario-64** [Ghezzo/BossesKilledLFR#3]
Currently two LFR raids are available in Dragonflight: Vault of the Incarnates and Aberrus the Shadowed Crucible, each with three wings. In previous expansions the addon would group the tabs for each raid together. Meaning in the UI you'd have 3 tabs for the current raid, three tabs for the previous raid, etc.

What I'm seeing now is they're all mixed up. Mine are showing in this order:

Aberrus - Discarded Works
Vault - Primal Bulwark
Vault - Caverns of Infusion
Aberrus - Fury of Giants
Vault - Fury of the Storm
Aberrus - Neltharion's Shadow 

This makes it extremely confusing to select your wing to queue for. I don't care about Vault any longer. The tabs should be grouped together by raid as before. Could you please fix this? Thank you

**Comment by mario-64** [comment]
10.1.5 does **not** fix this issue. Could you please investigate and resolve? Thank you.

**Comment by Ghezzo** [comment]
Sorry for the very late reply, been slacking. Seems to have fixed itself at some point?

**Comment by mario-64** [comment]
> Sorry for the very late reply, been slacking. Seems to have fixed itself at some point?

No. The issue is not fixed. Please re-open and investigate.  Tabs still show in the wrong order:

Aberrus - Discarded Works
Vault - Primal Bulwark
Vault - Caverns of Infusion
Aberrus - Fury of Giants
Vault - Fury of the Storm
Aberrus - Neltharion's Shadow
